//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZhpRedEntities : DbContext
    {
        public ZhpRedEntities()
            : base("name=ZhpRedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TRF_WeChatUserInfo> TRF_WeChatUserInfo { get; set; }
        public DbSet<TRP_Activity> TRP_Activity { get; set; }
        public DbSet<TRP_ActivityAwardDetail> TRP_ActivityAwardDetail { get; set; }
        public DbSet<TRP_Award> TRP_Award { get; set; }
        public DbSet<TRP_AwardCategory> TRP_AwardCategory { get; set; }
        public DbSet<TRP_AwardCategoryProportion> TRP_AwardCategoryProportion { get; set; }
        public DbSet<TRP_AwardDetail> TRP_AwardDetail { get; set; }
        public DbSet<TRP_AwardReceive> TRP_AwardReceive { get; set; }
        public DbSet<TRP_AwardType> TRP_AwardType { get; set; }
        public DbSet<TRP_AwardTypeProportion> TRP_AwardTypeProportion { get; set; }
        public DbSet<TRP_ClientLog> TRP_ClientLog { get; set; }
        public DbSet<TRP_Award_bak> TRP_Award_bak { get; set; }
        public DbSet<TRP_ClientLog_bak> TRP_ClientLog_bak { get; set; }
        public DbSet<View_Activity> View_Activity { get; set; }
        public DbSet<View_Award> View_Award { get; set; }
        public DbSet<View_AwardCategory> View_AwardCategory { get; set; }
        public DbSet<View_AwardDetail> View_AwardDetail { get; set; }
        public DbSet<View_AwardReceive> View_AwardReceive { get; set; }
        public DbSet<View_AwardType> View_AwardType { get; set; }
        public DbSet<View_ClientLog> View_ClientLog { get; set; }
        public DbSet<View_PreciousAward> View_PreciousAward { get; set; }
        public DbSet<TRP_OpenCount> TRP_OpenCount { get; set; }
        public DbSet<TRP_ScanCount> TRP_ScanCount { get; set; }
        public DbSet<TRP_QRCodeScanLimited> TRP_QRCodeScanLimited { get; set; }
    }
}
